apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps-sync.yaml

patches:
  - target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/interval
        value: 5m
